### ISSUE TITLE
Validar la version de Python

### ISSUE THREAD

**Issue by Snifer** [KernelPanicBlog/Script-Post-instalacion#1]
Se debe de comprobar la version de python que se esta usando y en el caso de ser 3 indicar el uso antes de que se ejecute.

**Comment by angelleon** [comment]
if sys.version[0] == "3":
#algun mensaje
else:
    main()

**Comment by neoranger** [comment]
Gracias por el dato!

**Comment by hgavidia** [comment]
Solventado en la rama testing Codigo 100% compatible con python 3.x y python 2.x
