### ISSUE TITLE
Hacer que la opcion back funcione en cada menu de la versión Testing

### ISSUE THREAD

**Issue by neoranger** [KernelPanicBlog/Script-Post-instalacion#11]
La opcion back debe volver al menu anterior y no llevarnos al menu principal del script. En la version estable y unstable funciona, la nueva implementacion es donde no funciona.

**Comment by hgavidia** [comment]
En el pull #16 ya esta solventado.

**Comment by neoranger** [comment]
Fixed in testing branch.
