### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by Madh93** [KernelPanicBlog/Script-Post-instalacion#15]
Manjaro usa por defecto Python 3, por lo que lo recomendable sería desarrollar el script para para la versión 3.

O al menos, avisar que sólo es compatible con Python 2.7.

**Comment by neoranger** [comment]
Gracias por la sugerencia. Vamos a hacer lo posible para pasarlo a Python3.

**Comment by Snifer** [comment]
Por el momento se tiene pensado tenerlo con Python 2, y posteriormente verlo de pasarlo a Python3 y segun lo comentado se agrego en el README que funciona con Python 2  muchas gracias por la sugerencia. 

Regards,
Snifer
