### ISSUE TITLE
Uso de ramas

### ISSUE THREAD

**Issue by Madh93** [KernelPanicBlog/Script-Post-instalacion#18]
Pienso que actualmente se está gestionando de manera incorrecta las ramas en el proyecto. Los nuevos cambios y pull request se están añadiendo en la rama `testing`, manteniendo en `master` la versión estable.

Creo que sería mejor y más cómodo ir añadiendo todos los cambios al `master`. Para mantener versiones, se pueden crear ramas específicas para cada versión, o hacer uso de los `tags` como se hacen en otros proyectos.

**Comment by neoranger** [comment]
Gracias por la sugerencia. Estamos en eso. Como hicimos una migracion grande de codigo y se implemento en estos dias y para no molestar a los usuarios que esten usando el script, decidimos dejar todo el testing para algo razonablemente estable y la rama unstable para que nosotros los devs estemos modificando a diestra y siniestra. Obviamente, el que quiera mas estabilidad puede usar la rama master donde de a poco vamos a ir sacando diferentes versiones.

Saludos!
