### ISSUE TITLE
I hate you Sniffer

### ISSUE THREAD

**Issue by ghost** [KernelPanicBlog/Script-Post-instalacion#21]
Pensando en la lógica del proceso de postinstalación, no sería bueno, que justo después del refresco de mirrors y keys, viniera la opción para elegir los repos más rápidos para que así cuando se llegue a la parte de la actualización, esta vaya más rápido? Porque ahora, hasta el que viene indicado como número 5, viene la actualización junto con el ordenado de los mirrors... Entonces, si se siguiera un orden lógico secuencial, como que no me cuadra mucho el asunto...

**Comment by Snifer** [comment]
Lastimosamente el odio no puede ser subsanado,  ya que el titulo del mismo no tiene relacion con lo que mencionas en tu comentario, te pido que realices en una proxima como se debe. 

Muchas gracias.
