### ISSUE TITLE
Menu 2-1 office

### ISSUE THREAD

**Issue by marceolmedo** [KernelPanicBlog/Script-Post-instalacion#25]
en el menu de instalacion de aplicaciones de oficina, la entrada libreoffice fresh y la entrada libreoffice stilll tienen el mismo numero de ingreso . Esto lleva a  confusion a la hora de instalar
![captura de pantalla de 2016-06-25 22-19-57](https://cloud.githubusercontent.com/assets/19561068/16365362/4f245742-3bd4-11e6-82d3-3966c3cd1c39.png)

**Comment by hgavidia** [comment]
Corregido, gracias.
