### ISSUE TITLE
Emuladores

### ISSUE THREAD

**Issue by Atheror** [KernelPanicBlog/Script-Post-instalacion#29]
Request: A su consideración, sería bueno integrar lo siguiente:
Hay una plataforma de emuladores fácil de usar como una consola llamada retroarch http://www.libretro.com/
Se pueden instalar todos los emuladores desde ahi en lugar de uno por uno.

actualmente son los siguientes paquetes del repositorio de la comunidad de arch

`retroarch libretro-desmume libretro-gambatte libretro-genesis-plus-gx libretro-mgba libretro-mupen64plus libretro-nestopia libretro-pcsx-rearmed libretro-reicast libretro-snes9x libretro-yabause libretro-overlays libretro-shaders retroarch-assets-xmb retroarch-autoconfig-udev`

**Comment by hgavidia** [comment]
Saludos @Atheror , se agregara al menu de Game en la proxima version de MPIS. 
sin embargo se mantendran las actuales opciones de dicho menu. 
Gracias por el feedback.
