### ISSUE TITLE
Actualizacion

### ISSUE THREAD

**Issue by marceolmedo** [KernelPanicBlog/Script-Post-instalacion#31]
Me parece que estaria bueno que el script se actualize solo.. digo, no tiene la opcion de actualizarse si npo es a travez de pacman u octopi..

**Comment by hgavidia** [comment]
Saludos @marceolmedo , se tiene pensado para una futura version activar la funcionalidad de auto-update. 
Gracias por el feedback

**Comment by hgavidia** [comment]
Se decidio, no implementar el auto-update, esto con motivo a que el paquete ya se encuentra en aur, adicional en las opciones se encuentra la actualizacion completa del sistema que con esto se actualizaria mpis.
