### ISSUE TITLE
opción necesaria

### ISSUE THREAD

**Issue by alebcasas** [KernelPanicBlog/Script-Post-instalacion#41]
Hola, creo que seria genial agregar alguna opción dentro de instalar aplicaciones que te dejé seleccionar todas las que queres instalar para no tener que hacerlo de una en una...desde ya muchas gracias y saludos!!!

**Comment by neoranger** [comment]
Vamos a tenerlo en cuenta. Gracias!

**Comment by hgavidia** [comment]
Se agrego la opcion en la rama unstable.
tendras una opcion en el menu de configuracion para activar la instalacion multiple. luego tendras q seleccionar las aplicaciones a instalar y por ultimo en el menu de instalar tendras una nueva opcion para instalar las aplicaciones seleccionas.
@alebcasas esperamos tu feedback.

**Comment by hgavidia** [comment]
se ha mejorado la funcion y ahora se llamara tasks cuenta con una opcion en la barra de menus, para ejecutar las tareas pendientes ademas se mostrara con un numero la cantidad de tareas pendiente. tambien permite agregar instalaciones, desinstalaciones y comandos de actualizacion sobre el sistema.
