### ISSUE TITLE
Programas que considero necesarios

### ISSUE THREAD

**Issue by RafaelAybar** [KernelPanicBlog/Script-Post-instalacion#42]
* Git (version controller)
* Visual studio code (similar as sublime text3)
* Docker
* Virtualbox

**Comment by neoranger** [comment]
Gracias, vamos c considerarlo y si podemos lo tenemos listo para la próxima versión estable. Estate atento a las versiones inestables o testing.

**Comment by RafaelAybar** [comment]
Echo en falta kdenlive también

**Comment by hgavidia** [comment]
se agrego 
- Kdenlive
-  git
- visual studio code
