### ISSUE TITLE
Problemas en Actualizar Sistema

### ISSUE THREAD

**Issue by alebcasas** [KernelPanicBlog/Script-Post-instalacion#43]
Hola, estoy intentando con la opcion 4) Actualizar todo el sistema y refrescar los mirrors, y da el siguiente error:

Opcion > 4
Traceback (most recent call last):
  File "/usr/bin/mpis", line 97, in main
    cmd_ = get_command(menu, option, "list")
  File "/usr/lib/python3.5/site-packages/mpislib/core.py", line 393, in get_command
    for pack in _app:
TypeError: 'NoneType' object is not iterable

Pd: ya probe con las versiones estable, beta y alpha, en todas da el mismo error

**Comment by hgavidia** [comment]
@alebcasas se ha corregido el error en el ultimo commit de la rama estable, Gracias por tu colaboracion.
