### ISSUE TITLE
Proceso de desinstalación poco eficiente

### ISSUE THREAD

**Issue by RafaelAybar** [KernelPanicBlog/Script-Post-instalacion#46]
Para simplificar la desinstalación, de paquetes, no es preguntarle al usuario qué desea borrar y que lo pasen a una variable para hacer un sudo pacman -Rs (variable introducida). Lo mismo para yaourt.
Mucho más rápido que ir navegado para borrar.
A su vez, echo en falta una opción que te permita buscar el nombre de la aplicación a instalar/borrar

**Comment by hgavidia** [comment]
Debido que la finalidad del Script es ayudar a los usuarios nuevos, consideramos que es peligroso dejar que el usuario introdusca el paquete que desea desintalar ya que puede ocasinar daños que lo deje sin sistema ademas implicaria la memorizacion de los paquetes. sin embargo si vemos factible agregar la opcion de busqueda de aplicaciones para ser marcada para instalacion o desinstalacion.

**Comment by hgavidia** [comment]
implementada la funcionalidad de busqueda, en la rama develop.
