### ISSUE TITLE
error en actualizar sistema y refrescar mirrors

### ISSUE THREAD

**Issue by marceolmedo** [KernelPanicBlog/Script-Post-instalacion#48]
en version 1.1 
opcion 0 opcion 4
sale un error.. transcribo a continuacion 
Opcion > 4
Se le pedira permisos de superusuario para realizar esta accion
Usted desea continuar? 
Si ó no

Opcion > s
[sudo] password for rucu: 
error: opción «-m» no válida
Error al ejecutar el comando
Tarea terminada con errores.
Pulse cualquier tecla para continuar ...

**Comment by neoranger** [comment]
Es un problema en la configuración del idioma de la aplicación. Si se setea la app en inglés, esa opción funciona perfectamente. Esto ya está solventado en la rama develop y será totalmente funcional cuando salga la próxima versión estable.

Saludos.
